### PR TITLE
tests: initial pytest proposal

### PR DESCRIPTION
**Pull request by jia200x**
This PR migrates the `test_bitarray.py` file into pytest.

Check the `README.md` file in the `tests` folder.
Run with `make pytest`

### CODE REVIEW

**Comment by adjih** [comment]
Test works well (MacOS / anaconda python), and also good model of how pytest can be used in the future. 

@dbarthel-ol @tanupoo  - I understand you know better the intended structure of the cleaned repository -> do you want to merge  by chance?

**Comment by tanupoo** [comment]
I like this.  No objection.  See further discussion is in the thread: https://github.com/orgs/openschc/teams/participants/discussions/16

**Comment by jia200x** [comment]
> https://github.com/orgs/openschc/teams/participants/discussions/16

For some reason I'm not able to follow the discussion. Sends 404.

BTW I tried to install `pytest` inside micropython. Unfortunately it fails:
```
MicroPython v1.10-230-ge0c6dfe90 on 2019-03-24; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import upip
>>> upip.install("pytest")
Installing to: /home/jialamos/.micropython/lib/
Warning: pypi.org SSL certificate is not validated
Error installing 'pytest': , packages may be partially installed
>>> import pytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'pytest'
```

**Comment by tanupoo** [comment]
Hi Jose,

I don't think micropython can work with pytest.  You can just use makefile in the tests directory instead.

Thanks,
Shoichi

**Pull request merged**
